title: Boston Microtechnology 
description: Boston Microtechnology is an NSF funded semiconductor startup located in the Greater Boston area working on the next generation power converter solution for the LED lighting and the Internet-of-Things industry. Awarded SBIR Phase 1 (Award 1913881) on 15 June 2019
theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true
lang: en
direction: auto

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
